import { useState } from 'react';
import { toast } from 'sonner';
import { Check, Copy, KeyRound, QrCode, ShieldCheck } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';

const STEP_LABELS = ['Confirm Password', 'Scan QR Code', 'Verify Code', 'Confirm', 'Recovery Codes'];
const MOCK_RECOVERY_CODES = ['XXXX-XXXX', 'XXXX-XXXX', 'XXXX-XXXX', 'XXXX-XXXX', 'XXXX-XXXX', 'XXXX-XXXX'];

function StepIndicator({ step }) {
  return (
    <div className="flex items-center gap-1.5">
      {STEP_LABELS.map((label, index) => {
        const stepNumber = index + 1;
        const isDone = stepNumber < step;
        const isActive = stepNumber === step;
        return (
          <div key={label} className="flex flex-1 items-center gap-1.5 last:flex-none">
            <span
              className={`flex size-6 shrink-0 items-center justify-center rounded-full text-xs font-medium ${
                isDone ? 'bg-emerald-500 text-white' : isActive ? 'bg-sky-600 text-white' : 'bg-slate-200 text-slate-500'
              }`}
            >
              {isDone ? <Check className="size-3.5" /> : stepNumber}
            </span>
            {stepNumber < STEP_LABELS.length && <span className={`h-px flex-1 ${isDone ? 'bg-emerald-500' : 'bg-slate-200'}`} />}
          </div>
        );
      })}
    </div>
  );
}

function SetupWizard({ onOpenChange, onComplete }) {
  const [step, setStep] = useState(1);
  const [password, setPassword] = useState('');
  const [verificationCode, setVerificationCode] = useState('');
  const [error, setError] = useState('');

  const goNext = () => {
    if (step === 1 && !password.trim()) {
      setError('Enter your current password to continue');
      return;
    }
    if (step === 3 && verificationCode.trim().length !== 6) {
      setError('Enter the 6-digit code from your authenticator app');
      return;
    }
    setError('');
    setStep((current) => Math.min(current + 1, 5));
  };

  const goBack = () => {
    setError('');
    setStep((current) => Math.max(current - 1, 1));
  };

  const handleFinish = () => {
    onComplete();
    onOpenChange(false);
    toast.success('Two-factor authentication enabled');
  };

  return (
    <>
      <StepIndicator step={step} />

      <div className="min-h-48 py-2">
        {step === 1 && (
          <div className="space-y-2">
            <p className="text-sm text-slate-600">Confirm your password to start setting up two-factor authentication.</p>
            <FieldLabel>Current Password</FieldLabel>
            <Input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="••••••••" />
          </div>
        )}

        {step === 2 && (
          <div className="space-y-3 text-center">
            <div className="mx-auto flex size-40 items-center justify-center rounded-lg border border-dashed border-slate-300 bg-slate-50">
              <QrCode className="size-10 text-slate-300" />
            </div>
            <p className="text-xs text-slate-500">
              Your authenticator QR code will be generated by the server once this feature is connected to the backend. Scan it
              with an app like Google Authenticator or Authy.
            </p>
            <div className="flex items-center justify-center gap-2 rounded-lg bg-slate-50 px-3 py-2 font-mono text-xs text-slate-500">
              <KeyRound className="size-3.5" />
              Setup key pending backend integration
              <Copy className="size-3.5" />
            </div>
          </div>
        )}

        {step === 3 && (
          <div className="space-y-2">
            <p className="text-sm text-slate-600">Enter the 6-digit verification code from your authenticator app.</p>
            <FieldLabel>Verification Code</FieldLabel>
            <Input
              value={verificationCode}
              onChange={(event) => setVerificationCode(event.target.value.replace(/\D/g, '').slice(0, 6))}
              placeholder="123456"
              className="font-mono tracking-[0.3em]"
            />
            <p className="text-xs text-slate-400">Your code will be verified by the server.</p>
          </div>
        )}

        {step === 4 && (
          <div className="space-y-2 text-center">
            <ShieldCheck className="mx-auto size-10 text-emerald-500" />
            <p className="text-sm font-medium text-slate-900">Ready to enable two-factor authentication</p>
            <p className="text-xs text-slate-500">
              From now on, you&apos;ll need your authenticator app in addition to your password to sign in.
            </p>
          </div>
        )}

        {step === 5 && (
          <div className="space-y-3">
            <p className="text-sm text-slate-600">
              Save these recovery codes somewhere safe. Each can be used once if you lose access to your authenticator app.
            </p>
            <div className="grid grid-cols-2 gap-2 rounded-lg bg-slate-50 p-3 font-mono text-sm text-slate-600">
              {MOCK_RECOVERY_CODES.map((code, index) => (
                <span key={index}>{code}</span>
              ))}
            </div>
            <p className="text-xs text-slate-400">Recovery codes will be generated by the server once this feature is connected to the backend.</p>
          </div>
        )}
      </div>

      {error && <p className="text-sm text-destructive">{error}</p>}

      <DialogFooter className="sm:justify-between">
        <Button type="button" variant="outline" onClick={step === 1 ? () => onOpenChange(false) : goBack}>
          {step === 1 ? 'Cancel' : 'Back'}
        </Button>
        {step < 5 ? (
          <Button onClick={goNext}>{step === 4 ? 'Confirm & Enable' : 'Continue'}</Button>
        ) : (
          <Button onClick={handleFinish}>Done</Button>
        )}
      </DialogFooter>
    </>
  );
}

export function TwoFactorSetupDialog({ open, onOpenChange, onComplete }) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Set Up Two-Factor Authentication</DialogTitle>
          <DialogDescription>Add an extra layer of security to your platform admin account.</DialogDescription>
        </DialogHeader>

        <SetupWizard key={open ? 'open' : 'closed'} onOpenChange={onOpenChange} onComplete={onComplete} />
      </DialogContent>
    </Dialog>
  );
}
